w3c/openscreenprotocol

- requirements.md
This document addresses part of Issue #1 ([Meta] Write document describing protocol requirements).  It has:
* Draft requirements for Presentation API (Issue #2)
* Partial draft of non-functional requirements (Issue #4)
This is an initial draft based on some of the content used to develop the charter [1], but streamlined.  Any feedback appreciated.
[1] https://github.com/webscreens/cg-charter/blob/gh-pages/requirements.md
> Initial draft of Open Screen requirements.

- device_specs.md
- requirements.md
For Issue #4: Non-functional requirements
PTAL @schien @tidoust @anssiko et al.
New content:
- Adds non-functional requirements around user experience.
- Adds a document listing specs of devices that might be used as controllers and receivers.
Editing:
- Link Presentation API terms to definitions in the spec.
- Clarify text in a few places.
- Improve capitalization and indentation consistency.
- Use more readable anchor names.
> Adds non-functional requirements for user experience.  Additional editing.

- templates/README.md
- templates/transport.md
For Issue #8: [Meta] Evaluate protocol transport mechanisms
> Template for transport evaluation

- README.md
- quic.md
- templates/README.md
- templates/transport.md
Addresses Issue #9: Evaluate QUIC as a protocol transport
Based on conversation with a QUIC developer in Chromium and evaluation of the spec, this is a draft evaluation of QUIC using the template in PR #16.
Many details need to be determined and also reconciled with the current draft specification; my initial review was based on the public documents on chromium.org, and not the current IETF draft.
So consider this a first draft :)
> Draft evaluation for QUIC.

- datachannel.md
> initial draft for evaluating Data Channel as the transport protocol.

- control_protocol.md
PTAL @schien @anssiko @tidoust @chrisn 
This is a draft of a wire format for the control protocol for the Presentation API.  It defines a generic message format supporting commands, events, and request/response pairs.  It should be possible to layer it on top of QUIC or an RTCDataChannel (with a few modifications in either case).
I define a few example messages using this format for presentation screen availability and presentation initiation.  I'll take any feedback on this draft and fill out the rest of the message definitions in another pull request.
If the feedback asks for major changes, then I will recommend that the author submit a separate side-by-side proposal :-)
> Issue 11 control protocol

- control_protocol.md
Continuing to finish Issue #11.
Adds the following to the presentation control protocol:
- Table defining message type ids
- Presentation Termination Request
- Presentation Termination Event
- Presentation Connection Close Event
- Presentation Application Message
> [Control Protocol] Adds messages for presentation connections.

- control_protocol.md
Addresses Issue #11: Presentation API control protocol
Defines Presentation Reciever Status, the last message in the Presentation API control protocol.
Application Message:
- Adds a Locale field.
- Adds special handling for empty text messages.
- Defines encoding of text messages.
- Other corrections.
> Adds Presentation Receiver status.

- ssdp.md
Addresses:
* Issue #25: [SSDP] Research history of uPnP exploits
* Issue #27: [SSDP] Investigate licensing requirements for uPnP
Specifically calls out SSDP amplification attacks, which are used today to launch DDoS attacks against Web services.  See Issue #57.
> Add text for SSDP licensing and security

- benchmarks/README.md
- benchmarks/transport.md
Addresses Issue #74: Performance data for transport protocols.
A benchmarking framework to compare QUIC and RTCDataChannel.
PTAL @schien  as you authored the RTC DataChannel proposal; other comments welcome as well.
> Adds transport benchmark design

- j-pake.md
This PR adds a document that summarizes the J-PAKE protocol described in [RFC 8236](https://datatracker.ietf.org/doc/rfc8236/), including:
- what types of messages must be exchanged between two parties
- two possible architectures: J-PAKE over a dedicated channel, and TLS with ECJ-PAKE
- open source implementations
I'd be happy if this would be useful for our discussion.
> Add a document about details on J-PAKE

- ssdp.md
Addresses Issue #57: [SSDP] Update proposed use of SSDP to specifically prevent SSDP amplification attacks.
This requires mitigations which will prevent an attacker from using an Open Screen Protocol implementation to target an external IP address with SSDP responses.
> Prevent SSDP amplification attacks

- CONTRIBUTING.md
- Makefile
- index.bs
- index.html
Hello,
To incorporate existing material and add new material from our F2F meeting in May, I'd like to start a combined document that I think will be easier to iterate on than the scattered set of existing documents.
Most of the material will be based on those documents or meeting minutes; however, I'd also like to make the technical descriptions more "spec like" using specific procedures and steps, and conformance terms.
Ideally, this will be substantially complete (as far as incorporating existing material) in advance of TPAC.
This PR adds three files:
- Spec outline using [Bikeshed](https://tabatkins.github.io/bikeshed/)
- Contribution mechanics (since we don't have one for SSCG)
- Simple Makefile to regenerate spec.
I will add a meta-issue to fill in sections after this is complete, …
> Outline for a combined specification document.

- index.bs
- index.html
Community Groups specs are published under the W3C Community Contributor License Agreement (CLA). Also, the Status of This Document (SOTD) section should be explicit that the document is not a W3C Standard and is not on the W3C Standards Track.
> Adjust copyright and SOTD sections to mention CLA

- index.bs
- index.html
Addresses Issue #99 to complete the introduction, terminology and requirements section (excepting that for Remote Playback API).  This is a lightly edited version of the content in [requirements.md](../requirements.md).
Note: Use the initialize-spec as the base branch for this PR.
Editor's notes:
A best effort was undertaken to leverage Bikeshed's autolinking functionality.  Specifically, the Second Screen specs are not in the Bikeshed database, so terms have to be defined in an "anchors" block at the beginning of the document.  In that block, I didn't see a way to define shortened forms, e.g. ("controller" for "controlling browsing context"), so they will need to be linked in the upstream spec, or perhaps there's a Bikeshed feature I'm missing.
> Adds terminology and requirements to spec.

- README.md
This adds a link to the draft spec to the ReadMe, using wording copied from the Abstract.
> Add link to Open Screen Protocol draft spec

- index.bs
The presentation-url-availability-* messages were changed to require
non-empty url and availibility lists, but the corresponding CDDL wasn't
changed.  This change just updates the CDDL spec to require a minimum of
one element for the relevant arrays.
> Add CDDL minimum occurrence specification

- README.md
- benchmarks/discovery.md
- benchmarks/transport.md
- control_protocol.md
- datachannel.md
- index.bs
- mdns.md
- quic.md
- schemes.md
- ssdp.md
Use absolute URLs so that the URLs remain valid even if directory structures change. Some links were already invalid.
> Replace GitHub issue relative URLs with absolute URLs

- index.bs
presentation-url-availability-event had a |urls| member when we were
considering whether it could send just a changed subset in each event.
The final text in the #presentation-protocol section doesn't describe
this member, so it should be removed.
> Remove unused urls in availability event

- index.bs
- index.html
Addresses Issue #13: Propose security mechanisms for the OSP
This is a draft version of the Security and Privacy section of the Open Screen Protocol spec, following the W3C's Security and Privacy Questionnaire [1].  It addresses the following:
* Threats
* Considerations specific to the OSP
* Considerations from the Security and Privacy sections of the Presentation API and Remote Playback API
* Some possible mitigations, with issues filed to investigate some specific areas further
Would appreciate wide review.  In particular, if there are topics from previous discussions missing, can add them here or in a followup PR.
[1] https://www.w3.org/TR/security-privacy-questionnaire/#questions
> Adds security and privacy section to the spec.

- index.bs
- index.html
- Add the protocol message for Remote Playback
- Add the mapping from API to messages
- Cleanup some terminology used by the Presentation API to make the two be in sync
- Switch everything to using the "definition list" of bikeshed, which seems like a better fit
> Add support for Remote Playback API (and some cleanup)

- index.bs
- index.html
This patch is a minor patch, focused on removing spelling errors and
cleaning up line endings, e.g. extra long lines and trailing whitespace.
> Cleanup line wrapping, spelling errors

- index.bs
- index.html
Currently, we consistently use integer keys in our object
definitions, with the human readable field name appended as a comment.
This unusual syntax has significant memory benefits for us, but could
use an explanation for people not familiar with this design.
> Add explanation of integer key usage

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
This patch adds specifications for getting device capabilities through the open screen protocol. Specifically, what types of actions and media does the receiver support?
NOTE: This patch is based on @pthatcherg's remote playback pull request, so make sure to exclude those commits when diffing!
> Add capabilities 

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
Update authentication section with authentication capabilities for pre-shared key ease of input and PSK input methods.
Add clarification that each authentication method requires its own specific messages.
Add CDDL message for authentication capabilities.
Remove certificate-fingerprint-pair message and fix description of format used for HKDF info in the proposed default authentication method.
> Authentication capabilities

- index.bs
Remove length prefixing
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/166.html" title="Last updated on May 17, 2019, 10:12 PM UTC (d750069)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/166/9adb019...d750069.html" title="Last updated on May 17, 2019, 10:12 PM UTC (d750069)">Diff</a>
> Remove length prefixing

- index.bs
- index.html
Specify that agents supporting PSK input must support numeric input as the default method.
Remove alphanumeric PSK input method.
Change receiver to server in tie-breaker when determining which agent presents the PSK.
***
<a href="https://pr-preview.s3.amazonaws.com/maxyakimakha/openscreenprotocol/pull/167.html" title="Last updated on May 20, 2019, 7:15 PM UTC (9e3fa75)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/167/056d1cf...maxyakimakha:9e3fa75.html" title="Last updated on May 20, 2019, 7:15 PM UTC (9e3fa75)">Diff</a>
> Clarify pre-shared key input section

- index.bs
- index.html
Addresses Issue #3: Requirements for the Remote Playback API.
These are derived from the Remote Playback Use Cases & Requirements doc [1] and the Remote Playback spec itself [2], specifically some of the implementation-specific steps and the non-normative notes for implementers.
[1] https://github.com/w3c/remote-playback/blob/gh-pages/use-cases.md
[2] https://w3c.github.io/remote-playback/
PTAL @pthatcherg
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/162.html" title="Last updated on May 22, 2019, 1:54 AM UTC (6f13996)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/162/fb68050...6f13996.html" title="Last updated on May 22, 2019, 1:54 AM UTC (6f13996)">Diff</a>
> Adds Remote Playback API requirements.

- index.bs
- index.html
- messages_appendix.cddl
This PR addresses issue #139 (Clarify scoping/uniqueness of request IDs) and issue #145 (Watch ID uniqueness).  In the Berlin F2F, we resolved to use a single per-agent counter and a state token to notify others when the counter is reset [1].
This PR also makes the following clarifications:
- agent-info is part of agent-info-response
- watch-id is always a uint
- Consolidates notes about ID lifetime/uniqueness and independence from connection lifetime into a single section.
[1] https://www.w3.org/2019/05/24-webscreens-minutes.html#x05
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/181.html" title="Last updated on Aug 8, 2019, 7:20 PM UTC (6458540)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/181/db6056d...645 …
> Allocation of request and watch IDs.

- index.bs
- index.html
- messages_appendix.cddl
This PR addresses the following issues:
- Issue #124: Is a Presentation close/terminate from a controller a request/response or event?
- Issue #137: How should presentation connections handle not receiving close response? 
- Issue #138: Remove presentation-connection-close-response message
Closing a presentation connection only needs to notify the agent at the other end of the connection.  It doesn't need a request and response.
This also makes the following changes:
- Breaks Presentation and Remote Playback protocols out into separate sections.
- Adds a Note: explaining why we have request and response for presentation termination.
- Adds a paragraph mapping the close event to a step in the Presentation API.
Discussion from Berlin F2F: …
> Remove presentation-request-close-request and response.

- index.bs
- index.html
- messages_appendix.html
This is a followup to https://github.com/webscreens/openscreenprotocol/pull/179.
It makes the following changes:
- Adds definitions for advertising agent, listening agent, display name, verified display name.
- Clarifies that truncated display names must never be shown to users.
- Clarifies that prefix check is required before the display name is verified.
- Replaced usages of "friendly name" with "display name."  (I could go through and autolink these usages if folks like, but maybe adding autolinks across the spec is better done in a separate PR.)
- Makes the usage of mDNS/DNS-SD a "must." This seems non-controversial to me, as it's the only discovery mechanism at present, but happy to do this in a separate PR if folks want to discuss.
***
<a …
> Additional changes related to PR #179 (agent display name).

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
This PR addresses Issue #131 (Mitigations for remote network attackers) by adding an unguessable token to the mDNS TXT record.
This token must be included in the first authentication message sent to/from the agent that advertises it, to prevent remote attackers from attempting authentication.
It also fixes a couple of typos in the authentication section and clarifies that SPAKE2 is mandatory for agents to implement.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/182.html" title="Last updated on Aug 14, 2019, 10:55 PM UTC (9ef6db6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/182/ec8c149...9ef6db6.html" title="Last updated on Aug 14, 2019, 10:55 PM UTC (9ef6db6)">Diff</a>
> Adds an unguessable token to mDNS.

- index.bs
- index.html
This PR adds a section describing how agents can use capability IDs to advertise support for non-standard message types.  It partially addresses Issue #175 (Add Extensibility section).
It also documents the message type ranges allocated to standard protocol messages, and extensions.
It's not a full Extensibility section, like the one for sensors.  It is mostly focused on how the mechanism to add extension messages to agents, versus guidance for authors on how to design extensions and how they interact with the standard protocols/features of OSP.  We can possibly expand the scope of this section later.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/183.html" title="Last updated on Aug 19, 2019, 6:54 PM UTC (ec26e51)">Preview</a> | <a …
> Describes protocol extensions and capability IDs.

- index.bs
- index.html
This is an action from the Berlin F2F [1] to ensure that advertising agents generate unique mDNS instance names.  This is already required by mDNS but calls it out specifically.
[1] https://www.w3.org/2019/05/23-webscreens-minutes.html#x03
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/186.html" title="Last updated on Aug 19, 2019, 8:07 PM UTC (d579f8f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/186/cb94381...d579f8f.html" title="Last updated on Aug 19, 2019, 8:07 PM UTC (d579f8f)">Diff</a>
> Add conflict resolution requirement for mDNS.

- index.bs
- index.html
Followup to PR #182 (mDNS token).  This renames the mDNS token from `pw` to `at` as suggested by @pthatcherg for consistency with the CBOR field.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/188.html" title="Last updated on Aug 20, 2019, 11:27 PM UTC (ef075d0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/188/9ffc015...ef075d0.html" title="Last updated on Aug 20, 2019, 11:27 PM UTC (ef075d0)">Diff</a>
> Replace pw with at.

- index.bs
- index.html
Resolves Issue #185: Consider making auth-initiation-token mandatory.
I don't see any disadvantage, at least for the local network discovery use case.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/189.html" title="Last updated on Aug 20, 2019, 11:33 PM UTC (55e0582)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/189/af6c432...55e0582.html" title="Last updated on Aug 20, 2019, 11:33 PM UTC (55e0582)">Diff</a>
> Make auth-initiation-token mandatory.

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
This addresses Issue #143: Notify endpoints when new connection is created.
It adds a presentation-change-event message that is sent to all other connected presentation controllers when a presentation receiver accepts an incoming connection request.
Discussed here at the F2F: https://www.w3.org/2019/05/23-webscreens-minutes.html#x22
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/187.html" title="Last updated on Aug 21, 2019, 4:09 PM UTC (3ab315d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/187/2164e92...3ab315d.html" title="Last updated on Aug 21, 2019, 4:09 PM UTC (3ab315d)">Diff</a>
> Adds presentation-change-event.

- index.bs
- messages_appendix.cddl
Reverts webscreens/openscreenprotocol#173.
Didn't mean to merge it.  Just wanted to rebase it.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/191.html" title="Last updated on Aug 21, 2019, 11:40 PM UTC (cfa548d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/191/3db2e11...cfa548d.html" title="Last updated on Aug 21, 2019, 11:40 PM UTC (cfa548d)">Diff</a>
> Revert "Add support for remoting."

- Makefile
- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
- scripts/cddl_lexer.py
- scripts/openscreen_cddl_dfns.py
- scripts/pygmentize_dir.py
This makes a number of changes to allow Bikeshed autolinking to work for CDDL message types defined by the spec:
1. Update the pygments lexer to treat top-level CDDL definitions as classes versus generic definitions.
2. Write a custom HTML formatter to wrap pygments classes in `<dfn>` tags.
3. But add a whitelist of messages autolinked in the document, to avoid Bikeshed from printing warnings for non-linked definitions.
4. Add autolinks to messages used in the Presentation API section of the document.
Incidental changes:
1. Update Makefile to regenerate HTML when the CDDL or the scripts are modified.
2. Rename a couple of anchors in the spec to not conflict with message definitions.
3. Fix a typo in presentation-url-availability-event.
4. Fix formatting of the capabilities enum. …
> Autolinking for CDDL message types.

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
- scripts/openscreen_cddl_dfns.py
Addresses F2F Action item [1]:
> ...add locale to agent-info and to create an agent-info event to advertise changes
[1] https://www.w3.org/2019/05/24-webscreens-minutes.html#x09
This adds a locales member to the `agent-info` dictionary that lists the user's preferred language tags.
It also adds an `agent-info-event` message that is broadcast to all connections when the content of `agent-info` has changed.
I believe the agent locales will be used to resolve Issue #146: Remote Playback HTTP headers.  However I didn't make any changes to the Remote Playback sections of the spec.
Additional changes:
- Autolinked to definitions of agent-info, agent-info-request, agent-info-response
- Removed a paragraph about extending agent-info, as this is covered in the Extensions section.
***
<a …
> Adds locales and agent-info-event.

- capabilities.md
- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
This is a markdown file listing known capabilities and their corresponding messages. 
Extensions could register their messages by adding to this file.
It also fixes duplicate numbering in the definition of `agent-capability` and adds links from the main spec.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/198.html" title="Last updated on Aug 28, 2019, 11:22 PM UTC (8e25af6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/198/4c4b287...8e25af6.html" title="Last updated on Aug 28, 2019, 11:22 PM UTC (8e25af6)">Diff</a>
> Adds an initial capabilities registry.

- index.bs
- index.html
This PR addresses Issue #118: UI guidelines for pairing and trusted/untrusted data.  
Action from the Berlin F2F: https://www.w3.org/2019/05/23-webscreens-minutes.html#x21
It adds a Security UI Considerations section with general guidelines on how metadata from agents should be presented to the user, and on PSK display and input. 
It also defines a "suspicious agent" as one that meets a criterion for a potential MITM attack.  The details on how to display a suspicious agent are moved to Security UI Considerations.
It also moves the description of how Instance Names should be handled into Security UI Considerations.
Finally it clarifies that any agents advertising a public key FP collision should be treated as suspicious (trusted or not) since we won't have any way to tell them apart.
*** …
> Adds Security UI Considerations.

- index.bs
- index.html
Addresses an open issue in the spec.  Fairly straightforward, so merging right away.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/205.html" title="Last updated on Aug 30, 2019, 6:30 PM UTC (d291b1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/205/d5f6386...d291b1c.html" title="Last updated on Aug 30, 2019, 6:30 PM UTC (d291b1c)">Diff</a>
> Adds RFC links to hash functions used in the spec.

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
Addresses #160: Refinements to Presentation API protocol.
- Adds an optional HTTP response code to presentation-start-request.
- Splits up the presentation-termination reason into two enums to make it clearer who requested termination, and why.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/204.html" title="Last updated on Aug 30, 2019, 6:01 AM UTC (6c79d1a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/204/d5f6386...6c79d1a.html" title="Last updated on Aug 30, 2019, 6:01 AM UTC (6c79d1a)">Diff</a>
> Small fixes to the presentation protocol.

- index.bs
- index.html
To finish drafting spec material for Issue #118: UI guidelines for pairing and trusted/untrusted data.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/202.html" title="Last updated on Aug 30, 2019, 3:36 AM UTC (f139572)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/202/d5f6386...f139572.html" title="Last updated on Aug 30, 2019, 3:36 AM UTC (f139572)">Diff</a>
> Adds an additional security UI guideline for PSK presentation.

- index.bs
- index.html
Follows up on https://github.com/webscreens/openscreenprotocol/issues/123#issuecomment-475760318:
> Should ensure that any capabilities disclosed before authentication are discussed in the Security & Privacy section, and the possible implications thereto.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/203.html" title="Last updated on Aug 30, 2019, 5:22 AM UTC (ccdc0e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/203/d5f6386...ccdc0e7.html" title="Last updated on Aug 30, 2019, 5:22 AM UTC (ccdc0e7)">Diff</a>
> Note that agent capabilities and other agent-info are public.

- index.bs
- index.html
Addresses Issue #144: Receiver/Controller/Agent terminology.
This PR updates the spec to allow agents to have the following roles:
- controller: initiates presentation/remote playback
- receiver: receives requests for presentation/remote playback
- media sender: sends media streams
- media receiver: receives media streams
- listening agent: mDNS listener/QUIC client
- advertising agent: mDNS responder/QUIC server
Unless the text is referring to a specific role it just uses the generic term "Open Screen agent" or "agent."
This update allows the requirements section to be simplified and references to unused terms to be dropped. 
Also, this PR makes it clear that roles must match an agent's advertised capabilities, and that an agent's support for APIs and streaming is based on capabilities …
> Fix terminology.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/206.html" title="Last updated on Sep 6, 2019, 12:28 AM UTC (0fafaed)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/206/948c6fb...0fafaed.html" title="Last updated on Sep 6, 2019, 12:28 AM UTC (0fafaed)">Diff</a>
> Add section about type key backwards compatibility.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/213.html" title="Last updated on Sep 6, 2019, 11:49 PM UTC (f14171b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/213/1ad67e8...f14171b.html" title="Last updated on Sep 6, 2019, 11:49 PM UTC (f14171b)">Diff</a>
> Specify codec names using RFC 6381

- index.bs
- index.html
This PR addresses the following action item from the Berlin F2F:
> ACTION: Mark Foltz to document which parts of the specs apply to which conformance class from an API perspective
This links API conformance classes to OSP capabilities, which in turn are linked to specific sets of messages.  Looking at this again, I plan to move the text around conformance into a different section before merging.
It also fixes some BS errors from previous PRs.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/214.html" title="Last updated on Sep 8, 2019, 5:49 PM UTC (a328f52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/214/38ccb1d...a328f52.html" title="Last updated on Sep 8, 2019, 5:49 PM UTC (a328f52)">Diff</a>
> Make relationship to API conformance classes more explicit.

- scripts/deploy.sh
The update drops the offending `rm` command that ended up erasing most of the contents of the repository upon deploy.
> Make sure deploy script does not delete content

- index.html
- schemes.md
Addresses Issue #93:  Add note to schemes.md about custom schemes and interop.
This adds a section noting interop challenges for browsers that support URL schemes other than `https`.
It also updates the existing text to align with the current terminology, adds links to some definitions/specs, and does some general copy-editing.
> Update schemes.md with interop notes.

- biblio.json
- index.bs
Several IETF standards on which the Open Screen Protocol is based appeared in the list of informative references instead of in the list of normative references.
The QUIC entry in the local biblio had the wrong title, and linked to a now outdated draft. The update lists referenced sections with their title instead of the section number (more explicit) in the list of custom definitions. The spec referenced the `APPLICATION_CLOSE` frame section in draft-16, which I believe got merged into the `CONNECTION_CLOSE` frame section in draft-23.
Also, the CDDL spec has now been published as RFC8610.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/openscreenprotocol/pull/236.html" title="Last updated on Oct 10, 2019, 10:54 AM UTC (80e8ace)">Preview</a> | <a …
> Make refs normative when needed, update QUIC and CDDL refs

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- index.bs
- w3c.json
Add required boilerplate files (code of conduct, license, w3c.json file) and update contributing rules and README to point to W3C's patent policy and Second Screen WG.
Also turn the draft spec into a proper WG Editor's Draft with the right copyright and license.
Note generation will only produce the right boilerplate once https://github.com/tabatkins/bikeshed/pull/1568 gets merged into Bikeshed. This PR should also only be merged once the transfer to `w3c/openscreenprotocol` is completed.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/openscreenprotocol/pull/238.html" title="Last updated on Dec 12, 2019, 5:33 PM UTC (329c99e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/238/c7cb098...tidoust:329c99e.html" title="Last updated on Dec …
> Prepare migration to W3C organization

- .travis.yml
Updates the travis-ci script/configuration to reflect the current recommended way to invoke bikeshed:
https://tabatkins.github.io/bikeshed/#travis-ci
> Attempt to fix travis-ci

- index.bs
Just a few drive-by editorial fixes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/245.html" title="Last updated on Oct 19, 2020, 5:06 PM UTC (15592e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/245/5312e98...15592e2.html" title="Last updated on Oct 19, 2020, 5:06 PM UTC (15592e2)">Diff</a>
> Fix a typo and dfn autolink

- index.bs
RFC8610 is not included in the Bikeshed bibliographic database yet.  Instead use a direct reference to the relevant section of the RFC.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/247.html" title="Last updated on Oct 19, 2020, 9:32 PM UTC (261bbc2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/247/d966069...261bbc2.html" title="Last updated on Oct 19, 2020, 9:32 PM UTC (261bbc2)">Diff</a>
> Editorial: fix reference to CDDL.

- index.bs
RFC 7049 has been replaced by standards-track [RFC 8949](https://tools.ietf.org/html/rfc8949).  According to RFC 8949,
```
This document obsoletes RFC 7049, providing editorial improvements,
new details, and errata fixes while keeping full compatibility with
the interchange format of RFC 7049.  It does not create a new version
of the format.
```
Therefore we can just refer to the new RFC.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/251.html" title="Last updated on Feb 23, 2021, 1:25 AM UTC (94c7613)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/251/ef6f97e...94c7613.html" title="Last updated on Feb 23, 2021, 1:25 AM UTC (94c7613)">Diff</a>
> Update reference to CBOR RFC.

- index.bs
This PR addresses editorial issues #219 and #220, that were resolved to remove profile- and extension-specific information from the usage of TLS 1.3.  Two parameters are retained that identify an incoming TLS connection request as intended for a specific OSP Agent.
Cipher and signature algorithm recommendations will likely be added back to this section in a later PR to close Issue #218.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/252.html" title="Last updated on Mar 1, 2021, 9:08 PM UTC (4dbe24d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/252/c3a7439...4dbe24d.html" title="Last updated on Mar 1, 2021, 9:08 PM UTC (4dbe24d)">Diff</a>
> Update TLS usage.

- index.bs
Reverts w3c/openscreenprotocol#252.  The travis-ci job to update index.html didn't complete before I merged.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/257.html" title="Last updated on Mar 1, 2021, 9:13 PM UTC (3847d11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/257/0764124...3847d11.html" title="Last updated on Mar 1, 2021, 9:13 PM UTC (3847d11)">Diff</a>
> Revert "Update TLS usage."

- scripts/deploy.sh
Attempt to fix #259 by referring to the environment variables directly, instead of indirectly.
Borrowed from the IntersectionObserver deploy.sh script.
> travis-ci: refer to variables directly.

- scripts/deploy.sh
Reverts w3c/openscreenprotocol#260.  This PR didn't make any difference, and it looks like a Travis issue, not a script bug.
Related to #259.
> Revert "travis-ci: refer to variables directly."

- index.bs
The `mv` parameter advertised through mDNS holds the metadata version, and is incremented each time the agent's metadata is changed.  This PR addresses issue #239 and specifies that it should be encoded as a QUIC variable-length integer, which is the same encoding we use throughout the protoocol.
It also updates cross references to point to the current RFC for QUIC.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/253.html" title="Last updated on Mar 1, 2021, 9:57 PM UTC (e3654e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/253/bf5f659...e3654e8.html" title="Last updated on Mar 1, 2021, 9:57 PM UTC (e3654e8)">Diff</a>
> Specify coding of mv.

- index.bs
A few minor fixes to close out Issue #148: Make a required/default remote playback state table.
- Clarifies why source is required in `remote-playback-start-response`
- Some copy editing
- Fix autolinks for `NETWORK_EMPTY` and `HAVE_NOTHING`
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/263.html" title="Last updated on Mar 3, 2021, 2:50 AM UTC (04d4118)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/263/5b7189f...04d4118.html" title="Last updated on Mar 3, 2021, 2:50 AM UTC (04d4118)">Diff</a>
> Clarify why source is required in remote-playback-start-response.

- index.bs
This adds an inline link to Issue #233 (Use the same codec names as the media APIs) which was left out of PR #267 since it wasn't labeled _v1-spec_.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/268.html" title="Last updated on Mar 3, 2021, 6:30 PM UTC (4154285)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/268/45df70d...4154285.html" title="Last updated on Mar 3, 2021, 6:30 PM UTC (4154285)">Diff</a>
> Add link to Issue 233.

- index.bs
This update converts all explicit references to the HTML spec to Bikeshed's autolinks syntax. To render the name of the interface along with the name of the attribute or method, the "visible text" syntax is used (the text after `|`).
The notions of "media error code", official playback position", "poster frame" and "timeline offset" are not HTMLMediaElement attributes but rather internal HTML concepts whose definitions are not currently exported. Longer term, we should make sure that the HTML spec exports these terms (unless we don't need them anymore).
The text incorrect referred to a `stalled` attribute that does not exist, instead of to the `stalled` event. Text updated accordingly.
This would address #264.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/269 …
> Convert HTMLMediaElements links to autolinks

- index.bs
This should add an appropriate "Latest published version:" link to the header now that we published the FPWD.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/272.html" title="Last updated on Mar 18, 2021, 10:46 AM UTC (05eef63)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/272/2c071ca...05eef63.html" title="Last updated on Mar 18, 2021, 10:46 AM UTC (05eef63)">Diff</a>
> Advertise TR URL in the spec

- .github/workflows/pr-push.yml
- CONTRIBUTING.md
To be merged after default branch has been renamed.
See #274.
> Update references to default branch to use "main"

- index.bs
The spec incorrectly referenced the `audio-encoding-offer` message from within the description of the video payload property.
Also, the description of the payload property mentioned the `format` field of `audio-encoding-offer` and `video-encoding-offer` messages, but these fields do not exist. This update references the `codec-name` field instead.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/openscreenprotocol/pull/289.html" title="Last updated on Jan 20, 2022, 11:32 PM UTC (372ed4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/289/e63d958...tidoust:372ed4e.html" title="Last updated on Jan 20, 2022, 11:32 PM UTC (372ed4e)">Diff</a>
> Fix a couple of typos: no "format" field and audio/video mix-up

- scripts/pygmentize_dir.py
Ensure pygmentize_dir.py runs under python3, and update the import for HtmlFormatter to the current one.
> Update pygmentize_dir.py for python3

- .github/workflows/auto-publish.yml
The spec-prod action was already used to deploy the generated spec to the `gh-pages` branch. This update tells the action to also deploy the spec as Working Draft to /TR.
The `ECHIDNA_TOKEN` token was added as secret in the repository settings.
> Enable auto-publication of WD to /TR

- scripts/pygmentize_dir.py
Pygments 2.12.0 removed the `outfile` argument from HtmlFormatter.wrap.
> Update pygmentize_dir.py for Pygments 2.13.0

- index.bs
Addresses Issue #287: Clarify time-scale field.
Adds a concrete definition of a time scale and cross-references from the messages that use it.
Here are some concrete examples of how it is used for video:
https://developer.apple.com/library/archive/qa/qa1447/_index.html
Let me know if further examples, explanation would be helpful.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/298.html" title="Last updated on Sep 12, 2022, 8:41 PM UTC (ee50420)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/298/e8e728c...ee50420.html" title="Last updated on Sep 12, 2022, 8:41 PM UTC (ee50420)">Diff</a>
> Explain what a time scale is.

- index.bs
Addresses Issue #277: Consider removing support for P-521
P-521 is a 521-bit elliptic curve that can be used to generate ECDSA certificates.  Although it's supported in TLS 1.3, it is not widely used in practice.
See [this thread on mozilla.dev.security.policy](https://groups.google.com/g/mozilla.dev.security.policy/c/7O34-DmZeC8?pli=1) for some discussion of the issues with P-521.  In short it offers little incremental security benefits over P-384, and ECC implementations are likely not very optimized.
So we're not going to make it an option for OSP agent certificates, so implementations don't need to support it.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/295.html" title="Last updated on Sep 8, 2022, 8:00 PM UTC (bcc0bc0)">Preview</a> | <a …
> Remove P-521 curve from agent certificate requirements

- index.bs
Addresses Issue #233: Use the same codec names as the media APIs.
Per the discussion in https://www.w3.org/2022/06/08-webscreens-minutes.html#t08, this updates the spec to refer explicitly to the WebCodecs registry to define codec strings for codecs in that registry.
It adds fallback language for additional codecs not defined in that registry, but if it is not sufficient to define the strings for additional codecs I would prefer to just remove the fallback language from this PR and address that separately.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/299.html" title="Last updated on Sep 9, 2022, 10:23 PM UTC (e104c11)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/299/e8e728c...e104c11.html" title="Last updated on Sep 9, …
> Reference WebCodecs registry for codec names.

- index.bs
Addresses #303: Cross-spec links are broken
Thanks to fixes upstream to Bikeshed the existing section and HTML references now work.
Thank you @tidoust!
This PR just tidies up a few xrefs.
(If we land PRs to export additional terms from other specs, we could reduce the size of the anchors block, but that's for another day.)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/302.html" title="Last updated on Oct 14, 2022, 8:55 PM UTC (42124c3)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/302/c2d4001...42124c3.html" title="Last updated on Oct 14, 2022, 8:55 PM UTC (42124c3)">Diff</a>
> Attempt to fix the spec.

- index.bs
- messages_appendix.cddl
Addresses Issue #194: [Remote Playback] Capabilities for HDR rendering and display
This adds two fields to the `receive-video-capability` message that allows the receiver to list the HDR metadata types and transfer functions that the media receiver can accept.
The values are used by reference from the corresponding enums in the Media Capabilities API.  This was discussed, briefly, in the minutes of the joint SSWG/Media WG meeting:
https://www.w3.org/2022/01/11-mediawg-minutes.html#t01
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/300.html" title="Last updated on Oct 31, 2022, 5:38 PM UTC (cd9280d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/300/37cef31...cd9280d.html" title="Last updated on Oct 31, 2022, 5:38 PM UTC …
> Add transfer-functions and hdr-metadata to video-capabilities.

- index.bs
- messages_appendix.cddl
Addresses:
*  Issue #279: The keyUsage name is digitalSignature, not signing
*  Issue #280: Clarify the supported signature algorithms for certificates
For the first item, it explicitly references the `keyUsage` bit for `digitalSigning`.
For the second item, I added a table that matches the TLS signature_scheme values to the `AlgorithmIdentifier` values that should be used in the certificate.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/288.html" title="Last updated on Oct 27, 2021, 6:25 AM UTC (f96a9d5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/288/7305111...f96a9d5.html" title="Last updated on Oct 27, 2021, 6:25 AM UTC (f96a9d5)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/2 …
> Fixes algorithm and signing fields in agent certificate.

- index.bs
Some of the references to the Presentation API and Remote Playback API no longer existed as such in the API specs: presentation, presentation id, and media resources. This update adjusts the references accordingly.
***
<a href="https://pr-preview.s3.amazonaws.com/tidoust/openscreenprotocol/pull/307.html" title="Last updated on Dec 8, 2022, 5:34 PM UTC (acc4e4c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/307/3f1f148...tidoust:acc4e4c.html" title="Last updated on Dec 8, 2022, 5:34 PM UTC (acc4e4c)">Diff</a>
> Fix broken references to API specs

- biblio.json
- index.bs
This PR wraps #82 by updating bibliographic references to QUIC to refer to the published RFC, RFC9000.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/310.html" title="Last updated on Sep 8, 2023, 9:43 PM UTC (5935b77)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/310/bbeb6e0...5935b77.html" title="Last updated on Sep 8, 2023, 9:43 PM UTC (5935b77)">Diff</a>
> Update QUIC references to RFC9000.

- capabilities.md
- messages_appendix.cddl
This addresses #254 by assigning remaining message types in the protocol to capabilities in the table.
A new capability `receive-data` is added to the table since there was no existing capability to receive message type 24 (data frames).
`video-request-format` was removed from the list of message definitions because there was no reference to it in the spec.
> Update capabilities table.

- index.bs
- messages_appendix.cddl
Addresses #266 by removing codec parameters from the `streaming-capabilities-response` message.
Full codec strings should carry sufficient information to describe the encoding.  For example, see the specification of the vp9 codec string:
https://github.com/webmproject/vp9-dash/blob/master/VPCodecISOMediaFileFormatBinding.md#codecs-parameter-string
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/312.html" title="Last updated on Oct 4, 2023, 10:28 PM UTC (c2cf850)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/312/212162c...c2cf850.html" title="Last updated on Oct 4, 2023, 10:28 PM UTC (c2cf850)">Diff</a>
> Remove codec parameters.

- index.bs
Addresses Issue #132.
Clarify how private browsing should be handled by OSP implementations.
Replaces "incognito" with "private browsing" and links to the TAG finding on private browsing.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/317.html" title="Last updated on Oct 4, 2023, 10:32 PM UTC (a65c00d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/317/212162c...a65c00d.html" title="Last updated on Oct 4, 2023, 10:32 PM UTC (a65c00d)">Diff</a>
> Update language around private browsing.

- index.bs
Addresses Issue #159.
This changes the maximum interval to send a `remote-playback-state-event` from the receiver to the controller to 250ms to align with HTML.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/316.html" title="Last updated on Sep 11, 2023, 12:03 AM UTC (401a081)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/316/212162c...401a081.html" title="Last updated on Sep 11, 2023, 12:03 AM UTC (401a081)">Diff</a>
> Change remote playback update interval to 250ms

- index.bs
- messages_appendix.cddl
Fixes #305.  This converts color-gamuts to be a single value, not a list, as support for a wider gamut implies support for narrower gamuts.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/311.html" title="Last updated on Oct 13, 2023, 10:21 PM UTC (7cd67df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/311/212162c...7cd67df.html" title="Last updated on Oct 13, 2023, 10:21 PM UTC (7cd67df)">Diff</a>
> Convert color-gamut to be a single value.

- index.bs
This addresses #107 and #108. 
For #107, I think the language about keeping cached mDNS records should be good enough.
For #108, we probably need a way for different capabilities in the protocol to "re-sync" their state after a network disconnection.  For example, a remote playback receiver would need to send a `remote-playback-state-event` message to update the sender on what the playback is doing. I'll have to think more about how to handle that scenario across the different capabilities in the protocol.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/318.html" title="Last updated on Oct 16, 2023, 4:38 PM UTC (a173b61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/318/dcc0efb...a173b61.html" title="Last updated on Oct 16, …
> Describe suspend and resume behavior.

- biblio.json
- index.bs
Addresses Issue #80 by adding an implementation note about message playback and placing an upper bound on message handling latency.
Basically for latency, "the lower the better," but this uses the ITU recommendation as an upper bound.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/319.html" title="Last updated on Oct 16, 2023, 5:17 PM UTC (0cdd969)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/319/ee2b93f...0cdd969.html" title="Last updated on Oct 16, 2023, 5:17 PM UTC (0cdd969)">Diff</a>
> Add note about maximum latency.

- index.bs
This PR addresses #218: Adjust cipher and signature algorithm preference list for hardware.
The required-to-implement algorithms in TLS 1.3 are suitable for the vast majority of hardware released in the past 10 years and should be forward compatible as well.
The spec can simply require TLS 1.3 and align the agent certificate definition with TLS 1.3 by requiring a 256-bit ECDSA public key.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/297.html" title="Last updated on Oct 16, 2023, 5:23 PM UTC (e4b8f5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/297/ee2b93f...e4b8f5c.html" title="Last updated on Oct 16, 2023, 5:23 PM UTC (e4b8f5c)">Diff</a>
> Simplify TLS requirements so we don't have to recommend algorithms.

- index.bs
Addresses Issue #282: Certificates should have a maximum lifetime, and SPAKE2 identities should be SPKI not cert fingerprint
This defines the agent fingerprint in terms of the SPKI (e.g., the public key) of the agent certificate.  The agent fingerprint is used to identify agents and is input to SPAKE2.
This allows agents to use shorter-lived certificates and renew their certificates without having to re-authenticate to other agents.
This PR does not specify certificate lifetimes or renewal policies.  It also does not handle the issuing of completely new certificates while maintaining previous trust relationships.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/301.html" title="Last updated on Jan 22, 2024, 8:26 PM UTC (596e9f3)">Preview</a> | <a …
> Define the agent fingerprint as the SPKI.

- index.bs
This addresses Issue #276: Agent Certificate has a circular dependency on itself
We can't use the certificate fingerprint as the serial number, because the serial number is embedded in the certificate itself.
X.509 requires every certificate from the same issuer to have a unique (not necessarily consecutive) serial number.
This PR adds a simple algorithm to generate a unique per-agent serial number per certificate.   Even if an agent generates a new certificate once per hour, the counter would take almost 500,000 years to overflow :-P
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/293.html" title="Last updated on Jan 22, 2024, 7:45 PM UTC (a90f8df)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/293/15ed7a5...a90f8df.html" …
> Add an algorithm for setting the agent certificate serial number

- index.bs
This resolves #333.  Unidirectional streams allow the writer to close immediately after the message is written.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/335.html" title="Last updated on May 31, 2024, 11:50 PM UTC (4581b3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/335/362a2fd...4581b3d.html" title="Last updated on May 31, 2024, 11:50 PM UTC (4581b3d)">Diff</a>
> Clarify QUIC stream usage.

- messages_appendix.cddl
The usage of `auth-spake2-handshake` was dropped by accident. This PR fixes it.
> Fix CDDL bug.

- .github/workflows/auto-publish.yml
The w3c/spec-prod action cleans files at the end of a build, and drops the CDDL messages appendices files that need to be imported to build the application and network specs.
Workaround here is to re-generate the messages files each time.
Fix for https://github.com/w3c/openscreenprotocol/pull/344#issuecomment-2364521197
> Fix generation of application and network specs

- index.bs
Addresses #334. 
MAX_STREAMS limits the number of QUIC streams that can be opened per connection.  Recommend a high value so that agents won't run into this limit in practice.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/336.html" title="Last updated on Sep 19, 2024, 6:44 PM UTC (880b286)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/336/9f704d4...880b286.html" title="Last updated on Sep 19, 2024, 6:44 PM UTC (880b286)">Diff</a>
> Add a NOTE about MAX_STREAMS for QUIC connections

- .github/workflows/auto-publish.yml
Bikeshed now requires Python 3.9+, which requires running jobs using a more recent version of Ubuntu.
> Bump version of Ubuntu and actions

- README.md
Replaces reference to OSP with Application and Network parts, switch to TRs for specs, update charter reference to the latest.
> Update README to reflect the latest status

- application.bs
- index.bs
- network.bs
This adds a note to the Status of This Document section of the previous Open Screen Protocol to note that the work was discontinued and redirect to the split documents (I copied the entire section because that makes life easier for Bikeshed, we shouldn't need to update that document any time soon in any case).
This also updates the references to IETF documents used in the Application and Network documents, and adds the links to the /TR versions.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/356.html" title="Last updated on Dec 11, 2024, 2:37 PM UTC (a78a59d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/356/ed2685d...a78a59d.html" title="Last updated on Dec 11, 2024, 2:37 PM UTC (a78a59d)">Diff</a>
> Add discontinued note, link to /TR, update refs

- .github/workflows/auto-publish.yml
The spec-prod action needs a couple of additional parameters that weren't set.
I'll add the Echidna tokens once #356 is merged (needed to have the right parameters in the documents themselves)
> Add missing parameters to enable auto-publication of split docs
