- quic.md
Somehow this got merged into the wrong branch.  Trying a new PR.
> Issue 9 quic

- requirements.md
This adds a requirement to allow extensibility of the base protocol to support experimentation and new use cases.
Addresses Issue #4: Non-functional requirements
> Addresses Issue #4: Adds a note about extensibility.

- ssdp.md
This is primarily a copy editing pass, although some new material was added (see below).
* It was reformatted to (more or less) 80 columns.
* Basic copy editing (grammar, sentence structure, etc.)
* Terms from SSDP highlighted in `code font`
* Make device/display/service/controller terminology more consistent (may be a bit more to do)
New material based on discussion in PR #20:
* Open questions were added to Method 2.
* Method 3 was added.
Three new issues were filed and linked from the evaluation:
* Issue #25: Research history of uPnP exploits
* Issue #26: Collect data regarding network and power efficiency
* Issue #27: Investigate licensing requirements for uPnP
> [SSDP] Editing to SSDP evaluation.

- ssdp.md
These didn't make the last PR.
* Link Issue #21 and Issue #22.
* Make service type consistent throughout.
> SSDP: A couple of more edits.

- datachannel.md
PTAL @schien 
This is some textual editing of the Data Channel evaluation.  It also replaces the TODOs with links to issues.
> Make edits

- ssdp.md
- templates/discovery.md
- templates/transport.md
This adds a template for evaluation of network discovery protocols (Issue #5) and tweaks the transport template to be consistent with that.
> Adds template for discovery & tweak transport template

- ssdp.md
FYI @louaybassbouss 
This PR reformats and reorders the sections of ssdp.md according to the template committed in PR #35.
It also adds a short note about hardware requirements which was missing in the original document.
> Reformat ssdp.md according to templates/discovery.md

- datachannel.md
- mdns.md
- requirements.md
- ssdp.md
A few minor typo and wording fixes
> Minor wording corrections

- mdns.md
Addresses Issue #39: [mDNS] Investigate history of mDNS exploits / security flaws.
Includes a list of known vulnerabilities and analysis of how to mitigate future vulnerabilities.
> Adds mDNS security history and analysis.

- control_protocol.md
Filling in more of the control protocol draft (Issue #11).  Includes minor corrections to existing message definitions.
> Presentation connection request and response message definitions.

- quic.md
- Links data collection TODOs to tasks in GitHub.
- Updates section on implementation.
- Updates links to Internet-Drafts for QUIC and TLS 1.3.
- Some other minor copy editing.
> Updates QUIC proposal.

- mdns.md
This CL simply adds Chrome OS to platform support.
R: @mfoltzgoogle
> Add Chrome OS to platform support

- README.md
- datachannel.md
- mdns.md
- quic.md
- ssdp.md
Short links do not seem to work in .md files, need to use absolute URLs instead.
> Fix links to issues

- device_specs.md
This pull requests adds device spec details for a 2015 Sony smart TV.
> Add TV device specs

- index.bs
- index.html
This fixes some Bikeshed errors and typos in the currently checked in Bikeshed spec.
It also regenerates the HTML from the spec, which includes the contents of PR #119 and PR #120.
> Fix some Bikeshed errors.

- index.html
- messages_appendix.cddl
- messages_appendix.html
These were messing up HTML formatting.
> Remove extra newlines from CDDL

- index.bs
- index.html
- messages_appendix.cddl
- messages_appendix.html
***
<a href="https://pr-preview.s3.amazonaws.com/maxyakimakha/openscreenprotocol/pull/178.html" title="Last updated on May 29, 2019, 9:26 PM UTC (de57333)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/178/3e4ad9b...maxyakimakha:de57333.html" title="Last updated on May 29, 2019, 9:26 PM UTC (de57333)">Diff</a>
> Authentication via SPAKE2

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/170.html" title="Last updated on May 31, 2019, 9:49 PM UTC (0a083c4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/170/fb68050...0a083c4.html" title="Last updated on May 31, 2019, 9:49 PM UTC (0a083c4)">Diff</a>
> Recommend zero-length QUIC connection IDs

- index.bs
- messages_appendix.cddl
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/171.html" title="Last updated on May 31, 2019, 11:27 PM UTC (9295e52)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/171/fb68050...9295e52.html" title="Last updated on May 31, 2019, 11:27 PM UTC (9295e52)">Diff</a>
> Add agent-capability type and agent-info.capabilities field

- index.bs
Add recommendation that agents display the complete (untruncated) display name
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/179.html" title="Last updated on Aug 2, 2019, 11:47 PM UTC (e82a275)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/179/68b6efb...e82a275.html" title="Last updated on Aug 2, 2019, 11:47 PM UTC (e82a275)">Diff</a>
> Add recommendation that agents display the complete display name

- index.bs
- messages_appendix.cddl
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/173.html" title="Last updated on May 23, 2019, 2:43 AM UTC (76ecd22)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/173/fb68050...76ecd22.html" title="Last updated on May 23, 2019, 2:43 AM UTC (76ecd22)">Diff</a>
> Add support for remoting.

- index.bs
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/207.html" title="Last updated on Sep 4, 2019, 8:05 PM UTC (790950c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/207/67fba6d...790950c.html" title="Last updated on Sep 4, 2019, 8:05 PM UTC (790950c)">Diff</a>
> Make sure PSK is the same for QR code and numeric PIN.

- index.bs
- messages_appendix.cddl
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/208.html" title="Last updated on Sep 4, 2019, 8:26 PM UTC (8922c46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/208/d75855b...8922c46.html" title="Last updated on Sep 4, 2019, 8:26 PM UTC (8922c46)">Diff</a>
> Add psk-min-bits-of-entropy

- index.bs
- messages_appendix.cddl
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/215.html" title="Last updated on Sep 8, 2019, 11:54 PM UTC (f4ed937)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/215/9754ca0...f4ed937.html" title="Last updated on Sep 8, 2019, 11:54 PM UTC (f4ed937)">Diff</a>
> Add supports-rotating to video capabilities

- index.bs
- index.html
This is an editorial PR to add links to newly filed issues.
***
<a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/pull/221.html" title="Last updated on Sep 11, 2019, 5:11 PM UTC (2af76d7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/221/09fc479...2af76d7.html" title="Last updated on Sep 11, 2019, 5:11 PM UTC (2af76d7)">Diff</a>
> Add Issues links.

- index.bs
- index.html
Fix a link that wasn't formatted properly.
***
<a href="https://pr-preview.s3.amazonaws.com/takumif/openscreenprotocol/pull/222.html" title="Last updated on Sep 11, 2019, 7:49 PM UTC (893cc20)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/222/29f6172...takumif:893cc20.html" title="Last updated on Sep 11, 2019, 7:49 PM UTC (893cc20)">Diff</a>
> Fix a link

- index.bs
- index.html
This addresses #148. AFAICT none of the fields is required to be in the initial state sent, but please let me know if I misunderstood this.
***
<a href="https://pr-preview.s3.amazonaws.com/takumif/openscreenprotocol/pull/217.html" title="Last updated on Sep 15, 2019, 9:49 PM UTC (d0d213b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webscreens/openscreenprotocol/217/dea1dce...takumif:d0d213b.html" title="Last updated on Sep 15, 2019, 9:49 PM UTC (d0d213b)">Diff</a>
> Add a table for Remote Playback controls and states

- capabilities.md
- index.bs
This addresses Issue #200 to clarify the descriptions of these two capabilities.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/255.html" title="Last updated on Mar 1, 2021, 11:20 PM UTC (9934410)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/255/bf5f659...9934410.html" title="Last updated on Mar 1, 2021, 11:20 PM UTC (9934410)">Diff</a>
> Update definitions of receives-audio and receives-video.

- index.bs
This PR updates inline issue links so that (nearly) all GH issues labeled _v1-spec_ are linked inline and also in the spec's Issue Index.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/pull/267.html" title="Last updated on Mar 3, 2021, 6:06 PM UTC (6312704)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/267/334c104...6312704.html" title="Last updated on Mar 3, 2021, 6:06 PM UTC (6312704)">Diff</a>
> Update issue links.

- explainer.md
> Add DIAL as an example protocol to the explainer.

- index.bs
Changes related to IPR policy considerations.
***
<a href="https://pr-preview.s3.amazonaws.com/eric-carlson/openscreenprotocol/pull/286.html" title="Last updated on Aug 13, 2021, 6:49 PM UTC (9c263e2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/openscreenprotocol/286/3d2f397...eric-carlson:9c263e2.html" title="Last updated on Aug 13, 2021, 6:49 PM UTC (9c263e2)">Diff</a>
> Proposed modifications to sections 9.2, 9.3, and 12.1.1

- network.bs
> Port #334 to the Open Screen Network Protocol document.

- images/entire_flow_chart.svg
Update the flow chart SVG for the changes in #332.
Also change the mDNS query to remove `.local` as that is not part of the query itself.
Finally I prettified the XML to make hand edits easier in the future.
> Reformat and update SVG.
